<?php

return [
    "tab_title" => "firstname",
    'module_name' => [
        'single' => 'Nieuw lid',
        'multiple' => 'Nieuwe leden',
    ],
    'fields' => [
        'locale' => [
            'active' => false,
            'type' => 'text',
            'title' => 'Taal',
            "read" => true,
            "required" => false,
        ],
        'company' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Bedrijf',
            "read" => true,
            "required" => false,
        ],
        'title' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Titel',
            "read" => true,
            "required" => false,
        ],
        'sex' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Geslacht',
            "read" => true,
            "required" => false,
        ],
        'firstname' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Voornaam',
            "read" => true,
            "required" => false,
        ],
        'lastname' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Achternaam',
            "read" => true,
            "required" => false,
        ],
        'email' => [
            'active' => true,
            'type' => 'email',
            'title' => 'E-mail',
            "read" => true,
            "required" => false,
        ],
        'phone' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Telefoon',
            "read" => true,
            "required" => false,
        ],
        'address' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Adres',
            "read" => true,
            "required" => false,
        ],
        'zipcode' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Postcode',
            "read" => true,
            "required" => false,
        ],
        'city' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Stad',
            "read" => true,
            "required" => false,
        ],
        'country' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Land',
            "read" => true,
            "required" => false,
        ],
        'birthdate' => [
            'active' => true,
            'type' => 'date',
            'title' => 'Geboortedatum',
            "read" => true,
            "required" => false,
        ],
        'newsletters' => [
            'active' => true,
            'type' => 'boolean',
            'title' => 'Nieuwsbrieven',
            "read" => true,
            "required" => false,
        ],
        'subject' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Onderwerp',
            "read" => true,
            "required" => false,
        ],
        'comment' => [
            'active' => true,
            'type' => 'textarea',
            'title' => 'Opmerkingen',
            "read" => true,
            "required" => false,
        ],
        'internal_contact' => [
            'active' => true,
            'type' => 'text',
            'title' => 'Interne Contactpersoon',
            "read" => true,
            "required" => false,
        ],
        'ip' => [
            'active' => true,
            'type' => 'text',
            'title' => 'IP-adres',
            "read" => true,
            "required" => false,
        ],
        'iban' => [
            'active' => true,
            'type' => 'text',
            'title' => 'IBAN',
            "read" => true,
            "required" => false,
        ],
    ],
];
